[build]
# The index HTML file to drive the bundling.
target = "index.html"
# Build in release mode.
release = true
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/"

# Whether to include hash values in the output file names.
filehash = true

[watch]
# Paths to watch. The default is to watch the entire project directory.
watch = ["src", "../core/src", "../charming-wrapper/src"]

# Paths to ignore. The default is to ignore nothing.
ignore = []

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true

[tools]
# Default wasm-bindgen version to use for the rust compiler.
wasm_bindgen = "0.2.122"
# Default wasm-opt version to use for the rust compiler.
wasm_opt = "version_130"